openapi: 3.0.0
info:
  title: MTG Daily Backend
  version: 1.0.0

servers:
  - url: "http://localhost:8080/api/v1"

paths:
  /search-cards:
    get:
      tags:
        - mtg
      operationId: searchCards
      summary: Get all card names
      description: Get all card names
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SearchCardsResponse'

  /firstHint:
    get:
      tags:
        - mtg
      operationId: getFirstHint
      summary: get first hint
      description: get first hint
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Hint'

  /guess:
    post:
      tags:
        - mtg
      operationId: guess
      summary: guess
      description: guess
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/GuessRequest"
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GameResponse'

components:
  schemas:
    Hint:
      type: object
      properties:
        hintNumber:
          type: integer
          description: number of hints
        givenHint:
          type: object
          properties:
            hintText:
              type: string
            hintValue:
              type: string

    GuessRequest:
      type: object
      required:
        - cardName
      properties:
        cardName:
          type: string
          description: Card name guessed


    GameResponse:
      type: object
      properties:
        numberOfGuesses:
          type: integer
          description: Number of guesses
        hintsProvided:
          type: array
          items:
            $ref: "#/components/schemas/Hint"
        gameStatus:
          type: string
        message:
          type: string
        guess:
          type: string
        isCorrect:
          type: boolean

    SearchCardsResponse:
      properties:
        cards:
          type: array
          items:
            type: object
            properties:
              id:
                type: string
              name:
                type: string
