openapi: 3.0.0
info:
  title: MTG Daily Backend
  version: 1.0.0

servers:
  - url: "http://localhost:8080/api/v1"

paths:
  /card:
    get:
      tags:
        - mtg
      operationId: getCard
      summary: get card
      description: get card
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CardResponse'

  /search-cards:
    get:
      tags:
        - mtg
      operationId: searchCards
      summary: search cards
      description: search cards
      parameters:
        - name: name
          in: query
          required: true
          description: Name of the card to search for
          schema:
            type: string
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SearchCardsResponse'

  /firstHint:
    get:
      tags:
        - mtg
      operationId: getFirstHint
      summary: get first hint
      description: get first hint
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Hint'

  /guess:
    post:
      tags:
        - mtg
      operationId: guess
      summary: guess
      description: guess
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/GuessRequest"
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GameResponse'

components:
  schemas:
    Hint:
      type: object
      properties:
        hintNumber:
          type: integer
          description: number of hints
        givenHint:
          type: object
          properties:
            hintText:
              type: string
            hintValue:
              type: string

    GuessRequest:
      type: object
      required:
        - cardName
      properties:
        cardName:
          type: string
          description: Card name guessed


    GameResponse:
      type: object
      properties:
        numberOfGuesses:
          type: integer
          description: Number of guesses
        hintsProvided:
          type: array
          items:
            $ref: "#/components/schemas/Hint"
        gameStatus:
          type: string
        message:
          type: string
        guess:
          type: string
        isCorrect:
          type: boolean

    SearchCardsResponse:
      type: object
      properties:
        content:
          type: array
          items:
            type: object
            properties:
              id:
                type: string
              name:
                type: string


    CardResponse:
      type: object
      properties:
        name:
          type: string
          description: The card's name.
        manaCost:
          type: string
          description: The mana cost required to play the card.
        colors:
          type: array
          items:
            type: string
          description: The card's colors.
        type:
          type: string
          description: card type
        rarity:
          type: string
          description: The rarity level of the card.
        set:
          type: string
          description: The set the card belongs to.
        setFullName:
          type: string
          description: The name of the set the card belongs to.
          x-java-name: setName #Maps to "setName" in JSON
        text:
          type: string
          description: The card's rules text.
        power:
          type: string
          description: The card's power, applicable to creatures.
        toughness:
          type: string
          description: The card's toughness, applicable to creatures.
        imageUrl:
          type: string
          description: URL to an image of the card.
        flavor:
          type: string
          description: Cards flavor text


