openapi: 3.0.0
info:
  title: MTG Daily Backend
  version: 1.0.0

servers:
  - url: "http://localhost:8080/api/v1"

paths:
  /initialize:
    get:
      tags:
        - mtg
      operationId: initialize
      summary: initialize session
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InitializeResponse'

  /hint:
    get:
      tags:
        - mtg
      operationId: getHint
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HintResponse'

components:
  schemas:
    GuessRequest:
      type: object
      required:
        - cardName
      properties:
        cardName:
          type: string
          description: Card name guessed

    HintResponse:
      type: object
      properties:
       hint:
         type: string
       numberOfGuesses:
         type: number
       maxGuesses:
         type: number

    SearchCardsResponse:
      properties:
        cards:
          type: array
          items:
            type: object
            properties:
              id:
                type: string
              name:
                type: string

    InitializeResponse:
      type: object
      properties:
        searchCardsResponse:
          $ref: '#/components/schemas/SearchCardsResponse'
        maxGuesses:
          type: number
        timeUntilReset:
          type: number
